/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucsb_pllab_tools_Measure */

#ifndef _Included_edu_ucsb_pllab_tools_Measure
#define _Included_edu_ucsb_pllab_tools_Measure

#ifdef __cplusplus
extern "C" {
#endif
	
/*
 * Class:     edu_ucsb_pllab_tools_Measure
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ucsb_pllab_tools_Measure_start
  (JNIEnv *, jclass);

/*
 * Class:     edu_ucsb_pllab_tools_Measure
 * Method:    stop
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_ucsb_pllab_tools_Measure_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
